site_name: Signals and Systems
theme:
  name: material
  palette:
    - scheme: dracula
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: teal
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home: index.md
  - Prerequisites:
      - Calculus Review: prerequisites/calculus-review.md
      - Linear Algebra Summary: prerequisites/linear-algebra-summary.md
  - Notes:
      - Random Variables: notes/random-variables.md
      - Expectation: notes/expectation.md
      - Convergence: notes/convergence.md
      - Markov Processes: notes/markov-processes.md
      - Ergodicity Explained: notes/ergodicity-explained.md
  - Projects:
      - Markov Chain Weather Sim: projects/markov-chain-weather.md
      - Poisson Process Sim: projects/poisson-process.md